### ISSUE TITLE
Card seen by Smart Card Connector but not by smart-ssh

### ISSUE THREAD

**Issue by ema** [FabianHenneke/smart-ssh#2]
Hi!

My Yubikey has been successfully identified by Smart Card Connector, but it's not listed among the readers in smart-ssh. I cannot thus use it in Secure Shell. 

![screenshot 2017-09-21 at 3 06 10 pm](https://user-images.githubusercontent.com/281102/30697592-d6bccb5c-9edf-11e7-88ef-40f3bf22bdc5.png)

Any ideas how to debug the issue? Thanks!

**Comment by fmeum** [comment]
Sorry for getting back to you so late, I had somehow turned off notifications.
Are you still facing this issue? The agent feature has meanwhile been integrated directly into Secure Shell (see the [setup guide](https://chromium.googlesource.com/apps/libapps/+/HEAD/nassh/doc/hardware-keys.md)). It would be helpful to know whether Secure Shell itself recognizes your Yubikey.
Further debug information can be obtained by enabling "Developer mode" under `chrome://extensions` and clicking on `Inspect views: background page` for the agent extension. The console tab may show an error message when you plug the key in again.

**Comment by ema** [comment]
Hey!

So, no, unfortunately it still does not work.

Here's secure shell logs:
![screenshot 2017-10-23 at 9 56 00 am](https://user-images.githubusercontent.com/281102/31878447-6ba21246-b7da-11e7-9435-f96555581839.png)

And smart card connector's:
![screenshot 2017-10-23 at 9 59 03 am](https://user-images.githubusercontent.com/281102/31878449-6e61936c-b7da-11e7-929d-640e5ff556c9.png)

**Comment by fmeum** [comment]
Thanks for providing me with the debug logs.

From the smart-ssh log I can tell that on the first try your YubiKey is recognized, but when queried for the public key responds with status code 0x65 0x81 "Memory failure". After that it is not recognized anymore as a smart card reader. I have to admit that I don't know what this error type is used for and whether it signals a hardware issue or could be caused by smart-ssh. Are you successfully using your Yubikey for SSH authentication on a non-Chromebook device?

The warnings shown by Smart Card Connector seem unrelated as they also appear for me. I will look into that too.

**Comment by fmeum** [comment]
I learned that the warnings are to be expected as per [this issue](https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/issues/53).

**Comment by ema** [comment]
Thanks @FabianHenneke. It looks like the issue might be due to how the key is generated. The key which does not work on chromeos was generated with [yubico-piv-tool](https://wikitech.wikimedia.org/wiki/Yubikey-SSH#Key.2Fcertificate_creation). After reading your reply I've created a new gpg key as per [yubico's doc](https://www.yubico.com/support/knowledge-base/categories/articles/use-yubikey-openpgp/) and that works like a charm on my chromebook.

**Comment by fmeum** [comment]
Glad to hear that @ema. 

Please note that the PIV and the OpenPGP applet on the Yubikey are completely separate applications that do not share any keys (not even PINs). I would thus guess that the "Memory failure" simply encoded the fact that your public key slots in the OpenPGP applet were empty.
